# Generated by Django 4.2.23 on 2025-08-21 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=10, unique=True)),
                ('descuento_comercial', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('margen_ganancia', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('margen_ganancia_efectivo', models.DecimalField(decimal_places=2, default=0.9, max_digits=5)),
                ('margen_ganancia_bulto', models.DecimalField(decimal_places=2, default=0.95, max_digits=5)),
            ],
            options={
                'indexes': [models.Index(fields=['abreviatura'], name='proveedores_abrevia_37f8f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.contacto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
        ),
    ]
