# Generated by Django 4.2.23 on 2025-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proveedores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Descuento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(default="Sin Descuento", max_length=50)),
                (
                    "efectivo",
                    models.DecimalField(decimal_places=2, default=0.1, max_digits=5),
                ),
                (
                    "bulto",
                    models.DecimalField(decimal_places=2, default=0.05, max_digits=5),
                ),
                ("cantidad_bulto", models.PositiveIntegerField(default=5)),
                (
                    "general",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("temporal", models.BooleanField(default=False)),
                ("desde", models.DateTimeField(blank=True, null=True)),
                ("hasta", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tipo"], name="precios_des_tipo_f8f05b_idx"),
                    models.Index(
                        fields=["desde", "hasta"], name="precios_des_desde_732777_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PrecioDeLista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "iva",
                    models.DecimalField(decimal_places=2, default=0.21, max_digits=5),
                ),
                (
                    "bulto",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proveedores.proveedor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["codigo"], name="precios_pre_codigo_d13dac_idx"
                    )
                ],
                "unique_together": {("proveedor", "codigo")},
            },
        ),
    ]
