# Generated by Django 5.2.4 on 2025-08-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='aplicar_umbral',
            field=models.BooleanField(default=False, help_text='Reservado para carrito: cuando sea True, el umbral (cantidad_bulto) podrá aplicarse en la lógica de carrito para crear ArticuloBulto. No afecta el cálculo de precios actual.'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='cantidad_bulto',
            field=models.PositiveIntegerField(default=5, help_text='No participa del cálculo actual; reservado para uso en carrito (futura implementación) para instanciar ArticuloBulto a partir de un umbral de cantidad.'),
        ),
    ]
