# Generated by Django 4.2.23 on 2025-08-21 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('precios', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('des_acumulada', models.TextField(blank=True)),
                ('stock_consolidado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos/')),
                ('descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.descuento')),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloSinRevisar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo_proveedor', models.CharField(max_length=50)),
                ('descripcion_proveedor', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('mapeado', 'Mapeado'), ('nuevo', 'Nuevo')], max_length=20)),
                ('fecha_mapeo', models.DateTimeField(blank=True, null=True)),
                ('descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.descuento')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(max_length=50)),
                ('descripcion_proveedor', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dividir', models.BooleanField(default=False)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articulos.articulo')),
                ('articulo_s_revisar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articulos.articulosinrevisar')),
                ('descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.descuento')),
                ('precio_de_lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precios.preciodelista')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
        ),
        migrations.AddIndex(
            model_name='articulosinrevisar',
            index=models.Index(fields=['proveedor', 'codigo_proveedor'], name='articulos_a_proveed_6b4fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='articulosinrevisar',
            index=models.Index(fields=['estado'], name='articulos_a_estado_2fbabf_idx'),
        ),
        migrations.AddIndex(
            model_name='articulosinrevisar',
            index=models.Index(fields=['codigo_barras'], name='articulos_a_codigo__1741ae_idx'),
        ),
        migrations.AddIndex(
            model_name='articuloproveedor',
            index=models.Index(fields=['proveedor', 'codigo_proveedor'], name='articulos_a_proveed_417c82_idx'),
        ),
        migrations.AddConstraint(
            model_name='articuloproveedor',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('articulo__isnull', False), ('articulo_s_revisar__isnull', True)), models.Q(('articulo__isnull', True), ('articulo_s_revisar__isnull', False)), _connector='OR'), name='one_relation_required'),
        ),
        migrations.AddConstraint(
            model_name='articuloproveedor',
            constraint=models.UniqueConstraint(fields=('precio_de_lista',), name='unique_ap_per_precio_de_lista'),
        ),
        migrations.AlterUniqueTogether(
            name='articuloproveedor',
            unique_together={('proveedor', 'codigo_proveedor')},
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['codigo_barras'], name='articulos_a_codigo__d3a22f_idx'),
        ),
    ]
