# Generated by Django 4.2.23 on 2025-08-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articuloproveedor',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('articulo__isnull', False), ('articulo_s_revisar__isnull', True)), models.Q(('articulo__isnull', True), ('articulo_s_revisar__isnull', False)), _connector='OR'), name='one_relation_required'),
        ),
    ]
