# Generated by Django 4.2.23 on 2025-08-17 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_articuloproveedor_one_relation_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulosinrevisar',
            name='usuario',
        ),
    ]
