# Generated by Django 5.2.4 on 2025-08-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_squashed_0003_remove_articulosinrevisar_usuario'),
        ('precios', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articuloproveedor',
            constraint=models.UniqueConstraint(fields=('precio_de_lista',), name='unique_ap_per_precio_de_lista'),
        ),
    ]
