# Generated by Django 4.2.23 on 2025-08-16 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('col_descripcion', models.CharField(blank=True, max_length=10, null=True)),
                ('col_precio', models.CharField(blank=True, max_length=10, null=True)),
                ('col_cant', models.CharField(blank=True, max_length=10, null=True)),
                ('col_iva', models.CharField(blank=True, max_length=10, null=True)),
                ('col_cod_barras', models.CharField(blank=True, max_length=10, null=True)),
                ('col_marca', models.CharField(blank=True, max_length=10, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'unique_together': {('proveedor',)},
            },
        ),
    ]
