# Generated by Django 5.2.4 on 2025-08-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configimportacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='configimportacion',
            name='instructivo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configimportacion',
            name='nombre_config',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='configimportacion',
            unique_together={('proveedor', 'nombre_config')},
        ),
        migrations.CreateModel(
            name='ArchivoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_csv', models.CharField(max_length=255)),
                ('hoja_origen', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('config_usada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='importaciones.configimportacion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
        ),
    ]
