# Generated by Django 5.2.4 on 2025-08-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0002_alter_configimportacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivopendiente',
            name='nombre_archivo_origen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
